//! Core IR → C code emitter.
//!
//! Vlang-style C backend: emit portable C99, let GCC/Clang handle optimization.
//! Compile with: zig cc -c -target x86_64-freestanding -ffreestanding -O2 kernel.c

use crate::core_ir::{Decl, Expr, LoopKind, Stmt, Typ, UnifiedModule};
use std::collections::HashSet;
use std::rc::Rc;

#[path = "c_backend_scan.rs"]
mod scan;
use scan::{check_module_limits, module_needs_invec};

fn ctype(typ: &Typ) -> String {
    match typ.canonical() {
        Typ::Int => "int64_t".into(),
        Typ::Bool => "uint8_t".into(),
        Typ::Float => "double".into(),
        Typ::String => "const char*".into(),
        Typ::Void => "void".into(),
        Typ::Array(inner) => format!("{}*", ctype(&inner)),
        // Matches native lower: Vec = { ptr, len, cap } (8-byte fields).
        Typ::Vector(_) => "struct InVec".into(),
        Typ::Named(name) if name == "Vec" || name == "InVec" => "struct InVec".into(),
        Typ::Named(name) => format!("struct {}", sanitize_ident(&name)),
        Typ::Generic(_) => "int64_t".into(),
    }
}

fn sanitize_ident(name: &str) -> String {
    name.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

fn escape_c_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\0' => out.push_str("\\0"),
            c if (c as u32) < 0x20 => {
                use std::fmt::Write;
                let _ = write!(out, "\\x{:02x}", c as u32);
            }
            c => out.push(c),
        }
    }
    out
}

fn sanitize_comment(s: &str) -> String {
    s.replace("*/", "* /").replace("/*", "/ *")
}

/// Emit a complete C translation unit from Core IR.
pub fn emit_c_module(module: &UnifiedModule) -> Result<String, String> {
    check_module_limits(module)?;

    let mut names = HashSet::new();
    for decl in &module.decls {
        match decl {
            Decl::Function { name, .. } => {
                names.insert(name.clone());
            }
            Decl::Class { methods, .. } => {
                for m in methods {
                    if let Decl::Function { name, .. } = m {
                        names.insert(name.clone());
                    }
                }
            }
            _ => {}
        }
    }
    let mut ctx = Ctx::new(Rc::new(names));

    ctx.line("/* Generated by Inauguration C backend */");
    ctx.line("#include <stdint.h>");
    ctx.line("#include <stddef.h>");
    ctx.line("");
    if module_needs_invec(module) {
        // Shared with native lower (ptr/len/cap, 8-byte fields).
        ctx.line("typedef struct InVec {");
        ctx.line("  int64_t *ptr;");
        ctx.line("  int64_t len;");
        ctx.line("  int64_t cap;");
        ctx.line("} InVec;");
        ctx.line("");
    }

    if let Some(pkg) = &module.identity.package {
        ctx.push(&format!("/* package: {} */", sanitize_comment(pkg)));
    }
    if let Some(mod_name) = &module.identity.module {
        ctx.push(&format!("/* module: {} */", sanitize_comment(mod_name)));
    }
    if module.identity.package.is_some() || module.identity.module.is_some() {
        ctx.line("");
    }

    for decl in &module.decls {
        if let Decl::Struct { name, fields, .. } = decl {
            ctx.push(&format!("struct {} {{", sanitize_ident(name)));
            ctx.indent();
            if fields.is_empty() {
                ctx.push("char _pad;");
            } else {
                for (fname, ftype) in fields {
                    ctx.push(&format!("{} {};", ctype(ftype), sanitize_ident(fname)));
                }
            }
            ctx.dedent();
            ctx.line("};");
            ctx.line("");
        }
    }

    // Classes lower as structs + free methods (self first param).
    for decl in &module.decls {
        if let Decl::Class {
            name,
            fields,
            methods,
            ..
        } = decl
        {
            ctx.push(&format!("struct {} {{", sanitize_ident(name)));
            ctx.indent();
            if fields.is_empty() {
                ctx.push("char _pad;");
            } else {
                for (fname, ftype) in fields {
                    ctx.push(&format!("{} {};", ctype(ftype), sanitize_ident(fname)));
                }
            }
            ctx.dedent();
            ctx.line("};");
            ctx.line("");
            for m in methods {
                if let Decl::Function {
                    name: mname,
                    params,
                    ret,
                    body,
                    ..
                } = m
                {
                    let mut full_params = vec![("self".to_string(), Typ::Named(name.clone()))];
                    full_params.extend(params.iter().cloned());
                    emit_fn_def(
                        &mut ctx,
                        &format!("{}_{}", sanitize_ident(name), sanitize_ident(mname)),
                        &full_params,
                        ret,
                        body,
                    );
                }
            }
        }
    }

    for decl in &module.decls {
        if let Decl::Interface { name, methods, .. } = decl {
            ctx.push(&format!("/* interface {} */", sanitize_ident(name)));
            for m in methods {
                let ps: Vec<String> = m
                    .params
                    .iter()
                    .map(|(n, t)| format!("{} {}", ctype(t), sanitize_ident(n)))
                    .collect();
                ctx.push(&format!(
                    "/* {} {}({}); */",
                    ctype(&m.ret),
                    sanitize_ident(&m.name),
                    ps.join(", ")
                ));
            }
            ctx.line("");
        }
    }

    let has_globals = module
        .decls
        .iter()
        .any(|d| matches!(d, Decl::Global { .. }));
    if has_globals {
        for decl in &module.decls {
            if let Decl::Global {
                name, typ, init, ..
            } = decl
            {
                let init_s = match init {
                    Some(e) => format!(" = {}", ctx.expr_str(e)),
                    None => String::new(),
                };
                ctx.push(&format!(
                    "volatile {} {}{};",
                    ctype(typ),
                    sanitize_ident(name),
                    init_s
                ));
            }
        }
        ctx.line("");
    }

    for decl in &module.decls {
        if let Decl::Function {
            name, params, ret, ..
        } = decl
        {
            let ps: Vec<String> = params
                .iter()
                .map(|(n, t)| format!("{} {}", ctype(t), sanitize_ident(n)))
                .collect();
            ctx.push(&format!(
                "{} {}({});",
                ctype(ret),
                sanitize_ident(name),
                ps.join(", ")
            ));
        }
    }
    if module
        .decls
        .iter()
        .any(|d| matches!(d, Decl::Function { .. }))
    {
        ctx.line("");
    }

    for decl in &module.decls {
        if let Decl::Function {
            name,
            params,
            ret,
            body,
            ..
        } = decl
        {
            emit_fn_def(&mut ctx, name, params, ret, body);
        }
    }

    for decl in &module.decls {
        if let Decl::Component {
            name,
            target,
            deterministic,
            ..
        } = decl
        {
            ctx.push(&format!(
                "/* component: {} target:{} deterministic:{} */",
                name, target, deterministic
            ));
        }
    }

    Ok(ctx.out)
}

struct Ctx {
    out: String,
    indent_lvl: u32,
    func_names: Rc<HashSet<String>>,
    /// Hoisted closures emitted before the current function.
    hoisted: Vec<String>,
    tmp: u32,
    ret_is_void: bool,
}

impl Ctx {
    fn new(func_names: Rc<HashSet<String>>) -> Self {
        Self {
            out: String::with_capacity(4096),
            indent_lvl: 0,
            func_names,
            hoisted: Vec::new(),
            tmp: 0,
            ret_is_void: false,
        }
    }

    fn fresh(&mut self, prefix: &str) -> String {
        let id = self.tmp;
        self.tmp += 1;
        format!("__{}_{}", prefix, id)
    }

    fn line(&mut self, s: &str) {
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn push(&mut self, s: &str) {
        for _ in 0..self.indent_lvl {
            self.out.push_str("  ");
        }
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn indent(&mut self) {
        self.indent_lvl += 1;
    }

    fn dedent(&mut self) {
        self.indent_lvl = self.indent_lvl.saturating_sub(1);
    }

    fn is_func(&self, name: &str) -> bool {
        self.func_names.contains(name)
    }

    fn expr_str(&mut self, expr: &Expr) -> String {
        match expr {
            Expr::IntLit(n) => format!("INT64_C({})", n),
            Expr::FloatLit(f) => {
                let bits = f.0;
                if bits.is_finite() {
                    format!("{:?}", bits)
                } else if bits.is_nan() {
                    "(0.0/0.0)".into()
                } else if bits.is_sign_negative() {
                    "(-1.0/0.0)".into()
                } else {
                    "(1.0/0.0)".into()
                }
            }
            Expr::BoolLit(b) => {
                if *b {
                    "1".into()
                } else {
                    "0".into()
                }
            }
            Expr::StringLit(s) => format!("\"{}\"", escape_c_string(s)),
            Expr::Ident(name) => {
                if self.is_func(name) {
                    format!("(uint64_t)({})", sanitize_ident(name))
                } else {
                    sanitize_ident(name)
                }
            }
            Expr::Binary { op, lhs, rhs } => {
                let (l, r) = (self.expr_str(lhs), self.expr_str(rhs));
                match op.as_str() {
                    "land" | "&&" => format!("({} && {})", l, r),
                    "lor" | "||" => format!("({} || {})", l, r),
                    "eq" | "==" => format!("({} == {})", l, r),
                    "neq" | "!=" => format!("({} != {})", l, r),
                    "lt" | "<" => format!("({} < {})", l, r),
                    "gt" | ">" => format!("({} > {})", l, r),
                    "le" | "<=" => format!("({} <= {})", l, r),
                    "ge" | ">=" => format!("({} >= {})", l, r),
                    "add" | "+" => format!("({} + {})", l, r),
                    "sub" | "-" => format!("({} - {})", l, r),
                    "mul" | "*" => format!("({} * {})", l, r),
                    "div" | "/" => format!("({} / {})", l, r),
                    "mod" | "%" => format!("({} % {})", l, r),
                    "band" | "&" => format!("({} & {})", l, r),
                    "bor" | "|" => format!("({} | {})", l, r),
                    "xor" | "^" => format!("({} ^ {})", l, r),
                    "shl" | "<<" => format!("({} << {})", l, r),
                    "shr" | ">>" => format!("({} >> {})", l, r),
                    _ => format!("({} /*op:{}*/ {})", l, sanitize_comment(op), r),
                }
            }
            Expr::Unary { op, expr } => {
                let e = self.expr_str(expr);
                match op.as_str() {
                    "neg" | "-" => format!("(-{})", e),
                    "not" | "!" => format!("(!{})", e),
                    "bnot" | "~" => format!("(~{})", e),
                    _ => format!("(/*op:{}*/{})", sanitize_comment(op), e),
                }
            }
            Expr::Call { callee, args } => {
                // method call: recv.method(args) → method(recv, args…)
                if let Expr::Field { base, name } = &**callee {
                    let mut as_ = vec![self.expr_str(base)];
                    as_.extend(args.iter().map(|a| self.expr_str(a)));
                    return format!("{}({})", sanitize_ident(name), as_.join(", "));
                }
                if let Expr::Ident(name) = &**callee {
                    self.intrinsic_or_call(name, args)
                } else {
                    let callee_s = self.expr_str(callee);
                    let as_: Vec<String> = args.iter().map(|a| self.expr_str(a)).collect();
                    format!("(({})({}))", callee_s, as_.join(", "))
                }
            }
            Expr::Field { base, name } => {
                format!("({}).{}", self.expr_str(base), sanitize_ident(name))
            }
            Expr::StructInit { name, fields } => {
                let fs: Vec<String> = fields
                    .iter()
                    .map(|(fn_, fe)| format!(".{} = {}", sanitize_ident(fn_), self.expr_str(fe)))
                    .collect();
                format!("((struct {}){{{}}})", sanitize_ident(name), fs.join(", "))
            }
            Expr::Index { base, index } => {
                format!("({})[{}]", self.expr_str(base), self.expr_str(index))
            }
            Expr::ArrayLit(items) => {
                let els: Vec<String> = items.iter().map(|e| self.expr_str(e)).collect();
                // Compound literal of int64_t; caller must keep storage live.
                format!(
                    "((int64_t[]){{{}}})",
                    if els.is_empty() {
                        "0".into()
                    } else {
                        els.join(", ")
                    }
                )
            }
            Expr::Closure {
                params,
                ret,
                body,
                captures,
            } => {
                let cname = self.fresh("closure");
                let env_name = format!("{}_env", cname);
                let mut helper = String::new();
                // Captures use file-scope static env so value stays a uint64_t fn ptr.
                // ponytail: not re-entrant / not thread-safe; heap env if that matters.
                if !captures.is_empty() {
                    helper.push_str(&format!("struct {} {{\n", env_name));
                    for cap in captures {
                        helper.push_str(&format!("  int64_t {};\n", sanitize_ident(cap)));
                    }
                    helper.push_str(&format!("}}\nstatic struct {} {};\n", env_name, env_name));
                }
                let ps: Vec<String> = params
                    .iter()
                    .map(|(n, t)| format!("{} {}", ctype(t), sanitize_ident(n)))
                    .collect();
                helper.push_str(&format!(
                    "static {} {}({}) {{\n",
                    ctype(ret),
                    cname,
                    ps.join(", ")
                ));
                let mut nested = Ctx::new(self.func_names.clone());
                nested.ret_is_void = matches!(ret.canonical(), Typ::Void);
                nested.indent_lvl = 1;
                for cap in captures {
                    let n = sanitize_ident(cap);
                    nested.push(&format!("int64_t {} = {}.{};", n, env_name, n));
                }
                let mut locals = Vec::new();
                collect_locals(body, &mut locals);
                for (n, ty) in &locals {
                    if captures.iter().any(|c| sanitize_ident(c) == *n) {
                        continue;
                    }
                    nested.push(&format!("{} {};", ty, n));
                }
                for s in body {
                    emit_stmt(&mut nested, s);
                }
                if nested.ret_is_void && !body.last().is_some_and(|s| matches!(s, Stmt::Return(_)))
                {
                    nested.push("return;");
                }
                helper.push_str(&nested.out);
                helper.push_str("}\n");
                self.hoisted.push(helper);
                if captures.is_empty() {
                    format!("(uint64_t)({})", cname)
                } else {
                    let fills: Vec<String> = captures
                        .iter()
                        .map(|cap| {
                            let n = sanitize_ident(cap);
                            format!("{}.{} = {}", env_name, n, n)
                        })
                        .collect();
                    format!("({{ {}; (uint64_t)({}); }})", fills.join("; "), cname)
                }
            }
        }
    }

    fn intrinsic_or_call(&mut self, name: &str, args: &[Expr]) -> String {
        let evaled: Vec<String> = args.iter().map(|e| self.expr_str(e)).collect();
        let a = |i: usize| -> String { evaled.get(i).cloned().unwrap_or_else(|| "0".into()) };
        match name {
            "outb" => {
                let p = a(0);
                let v = a(1);
                format!(
                    "__extension__({{ __asm__ volatile(\"outb %0, %1\" : : \"a\"((uint8_t)({v})) , \"Nd\"((uint16_t)({p})) : \"memory\"); }})"
                )
            }
            "inb" => {
                let p = a(0);
                format!(
                    "__extension__({{ uint8_t _v; __asm__ volatile(\"inb %1, %0\" : \"=a\"(_v) : \"Nd\"((uint16_t)({p})) : \"memory\"); _v; }})"
                )
            }
            "outl" => {
                let p = a(0);
                let v = a(1);
                format!(
                    "__extension__({{ __asm__ volatile(\"outl %0, %1\" : : \"a\"((uint32_t)({v})) , \"Nd\"((uint16_t)({p})) : \"memory\"); }})"
                )
            }
            "inl" => {
                let p = a(0);
                format!(
                    "__extension__({{ uint32_t _v; __asm__ volatile(\"inl %1, %0\" : \"=a\"(_v) : \"Nd\"((uint16_t)({p})) : \"memory\"); _v; }})"
                )
            }
            "hlt" => "__extension__({ __asm__ volatile(\"hlt\" : : : \"memory\"); })".into(),
            "cli" => "__extension__({ __asm__ volatile(\"cli\" : : : \"memory\"); })".into(),
            "sti" => "__extension__({ __asm__ volatile(\"sti\" : : : \"memory\"); })".into(),
            "invlpg" => format!(
                "__extension__({{ __asm__ volatile(\"invlpg (%0)\" : : \"r\"({}) : \"memory\"); }})",
                a(0)
            ),
            "lidt" => format!(
                "__extension__({{ __asm__ volatile(\"lidt (%0)\" : : \"r\"({}) : \"memory\"); }})",
                a(0)
            ),
            "read_cr2" => {
                "__extension__({ uint64_t _v; __asm__ volatile(\"mov %%cr2, %0\" : \"=r\"(_v)); _v; })"
                    .into()
            }
            "load8" => format!("(*(volatile uint8_t*)({}))", a(0)),
            "load16" => format!("(*(volatile uint16_t*)({}))", a(0)),
            "load32" => format!("(*(volatile uint32_t*)({}))", a(0)),
            "load64" => format!("(*(volatile uint64_t*)({}))", a(0)),
            "store8" => format!(
                "__extension__({{ *(volatile uint8_t*)({}) = (uint8_t)({}); }})",
                a(0),
                a(1)
            ),
            "store16" => format!(
                "__extension__({{ *(volatile uint16_t*)({}) = (uint16_t)({}); }})",
                a(0),
                a(1)
            ),
            "store32" => format!(
                "__extension__({{ *(volatile uint32_t*)({}) = (uint32_t)({}); }})",
                a(0),
                a(1)
            ),
            "store64" => format!(
                "__extension__({{ *(volatile uint64_t*)({}) = (uint64_t)({}); }})",
                a(0),
                a(1)
            ),
            "invoke" if args.len() == 1 => {
                format!("((uint64_t(*)(uint64_t))({}))({})", a(0), a(0))
            }
            "invoke" if args.len() == 2 => {
                format!("((uint64_t(*)(uint64_t))({}))({})", a(0), a(1))
            }
            "invoke" if args.len() == 3 => {
                format!(
                    "((uint64_t(*)(uint64_t,uint64_t))({}))({}, {})",
                    a(0),
                    a(1),
                    a(2)
                )
            }
            "invoke1" if args.len() == 2 => {
                format!("((uint64_t(*)(uint64_t))({}))({})", a(0), a(1))
            }
            "invoke2" if args.len() == 3 => {
                format!(
                    "((uint64_t(*)(uint64_t,uint64_t))({}))({}, {})",
                    a(0),
                    a(1),
                    a(2)
                )
            }
            _ => {
                let as_: Vec<String> = args.iter().map(|a| self.expr_str(a)).collect();
                format!("{}({})", sanitize_ident(name), as_.join(", "))
            }
        }
    }
}

fn emit_fn_def(ctx: &mut Ctx, name: &str, params: &[(String, Typ)], ret: &Typ, body: &[Stmt]) {
    let ps: Vec<String> = params
        .iter()
        .map(|(n, t)| format!("{} {}", ctype(t), sanitize_ident(n)))
        .collect();
    let sec = if name == "kernel_entry" {
        " __attribute__((section(\".text.entry\")))"
    } else {
        ""
    };
    let attr = format!("__attribute__((used)){}", sec);
    let sig = format!(
        "{} {} {}({})",
        attr,
        ctype(ret),
        sanitize_ident(name),
        ps.join(", ")
    );

    // Build body into a nested buffer so hoisted closures land before the fn.
    let mut body_ctx = Ctx::new(ctx.func_names.clone());
    body_ctx.tmp = ctx.tmp;
    body_ctx.ret_is_void = matches!(ret.canonical(), Typ::Void);
    body_ctx.indent_lvl = 1;

    let mut locals: Vec<(String, String)> = Vec::new();
    collect_locals(body, &mut locals);
    // iterator / match temps
    collect_loop_bindings(body, &mut locals);
    for (n, ty) in &locals {
        body_ctx.push(&format!("{} {};", ty, n));
    }
    // runtime error flag for throw/try/propagate (function-local, simple model)
    body_ctx.push("int __in_err = 0;");
    body_ctx.push("int64_t __in_err_val = 0;");

    for stmt in body {
        emit_stmt(&mut body_ctx, stmt);
    }
    if body_ctx.ret_is_void && !body.last().is_some_and(|s| matches!(s, Stmt::Return(_))) {
        body_ctx.push("return;");
    }

    ctx.tmp = body_ctx.tmp;
    for h in body_ctx.hoisted.drain(..) {
        ctx.out.push_str(&h);
        ctx.out.push('\n');
    }

    ctx.push(&format!("{} {{", sig));
    ctx.out.push_str(&body_ctx.out);
    ctx.line("}");
    ctx.line("");
}

fn emit_stmt(ctx: &mut Ctx, stmt: &Stmt) {
    match stmt {
        Stmt::Let(name, _, expr) => {
            let rhs = ctx.expr_str(expr);
            ctx.push(&format!("{} = {};", sanitize_ident(name), rhs));
        }
        Stmt::Assign(name, expr) => {
            let rhs = ctx.expr_str(expr);
            ctx.push(&format!("{} = {};", sanitize_ident(name), rhs));
        }
        Stmt::IndexAssign { base, index, value } => {
            let b = ctx.expr_str(base);
            let i = ctx.expr_str(index);
            let v = ctx.expr_str(value);
            ctx.push(&format!("({})[{}] = {};", b, i, v));
        }
        Stmt::FieldAssign { base, name, value } => {
            let b = ctx.expr_str(base);
            let v = ctx.expr_str(value);
            ctx.push(&format!("({}).{} = {};", b, sanitize_ident(name), v));
        }
        Stmt::Return(e) => match e {
            Some(x) => {
                let v = ctx.expr_str(x);
                ctx.push(&format!("return {};", v));
            }
            None => ctx.push("return;"),
        },
        Stmt::If {
            cond,
            then_body,
            else_body,
        } => {
            let c = ctx.expr_str(cond);
            ctx.push(&format!("if ({}) {{", c));
            ctx.indent();
            for s in then_body {
                emit_stmt(ctx, s);
            }
            ctx.dedent();
            if !else_body.is_empty() {
                ctx.line("} else {");
                ctx.indent();
                for s in else_body {
                    emit_stmt(ctx, s);
                }
                ctx.dedent();
            }
            ctx.line("}");
        }
        Stmt::Loop { kind, cond, body } => {
            match kind {
                LoopKind::For { binding } => {
                    // cond = iterable. Prefer InVec {ptr,len} layout from native lower.
                    let iter = cond
                        .as_ref()
                        .map(|c| ctx.expr_str(c))
                        .unwrap_or_else(|| "((struct InVec){0})".into());
                    let idx = ctx.fresh("i");
                    let len = ctx.fresh("len");
                    let ptr = ctx.fresh("ptr");
                    let vec = ctx.fresh("vec");
                    let bind = sanitize_ident(binding.trim().trim_start_matches("& "));
                    ctx.push(&format!("struct InVec {} = {};", vec, iter));
                    ctx.push(&format!("int64_t* {} = (int64_t*)({}.ptr);", ptr, vec));
                    ctx.push(&format!("int64_t {} = {}.len;", len, vec));
                    ctx.push(&format!(
                        "for (int64_t {} = 0; {} < {}; {}++) {{",
                        idx, idx, len, idx
                    ));
                    ctx.indent();
                    if bind != "_" && !bind.is_empty() {
                        ctx.push(&format!("{} = {}[{}];", bind, ptr, idx));
                    }
                    for s in body {
                        emit_stmt(ctx, s);
                    }
                    ctx.dedent();
                    ctx.line("}");
                }
                LoopKind::While | LoopKind::Infinite => {
                    match cond {
                        Some(c) => {
                            let cstr = ctx.expr_str(c);
                            ctx.push(&format!("while ({}) {{", cstr));
                        }
                        None => ctx.line("while (1) {"),
                    }
                    ctx.indent();
                    for s in body {
                        emit_stmt(ctx, s);
                    }
                    ctx.dedent();
                    ctx.line("}");
                }
            }
        }
        Stmt::Match { scrutinee, arms } => {
            // Simple if/else chain; patterns are source text (Core IR stores pattern strings).
            let scr_tmp = ctx.fresh("scr");
            let scr = ctx.expr_str(scrutinee);
            ctx.push(&format!("int64_t {} = (int64_t)({});", scr_tmp, scr));
            let mut first = true;
            for arm in arms {
                let (cond, binds) = match_arm_cond_and_binds(&scr_tmp, &arm.pattern);
                if first {
                    ctx.push(&format!("if ({}) {{", cond));
                    first = false;
                } else {
                    ctx.push(&format!("}} else if ({}) {{", cond));
                }
                ctx.indent();
                for b in binds {
                    ctx.push(&b);
                }
                for s in &arm.body {
                    emit_stmt(ctx, s);
                }
                ctx.dedent();
            }
            if !first {
                ctx.line("}");
            }
        }
        Stmt::Throw(e) => {
            let val = ctx.expr_str(e);
            ctx.push(&format!("__in_err = 1; __in_err_val = (int64_t)({});", val));
            if ctx.ret_is_void {
                ctx.push("return;");
            } else {
                ctx.push("return 0;");
            }
        }
        Stmt::Try { body, catches } => {
            ctx.line("{ /* try */");
            ctx.indent();
            ctx.push("int __in_err_save = __in_err;");
            ctx.push("__in_err = 0;");
            for s in body {
                emit_stmt(ctx, s);
            }
            if !catches.is_empty() {
                ctx.push("if (__in_err) {");
                ctx.indent();
                for (i, c) in catches.iter().enumerate() {
                    let bind = c.pattern.trim();
                    let (cond, binds) = match_arm_cond_and_binds("__in_err_val", bind);
                    if i == 0 {
                        ctx.push(&format!("if ({}) {{", cond));
                    } else {
                        ctx.push(&format!("}} else if ({}) {{", cond));
                    }
                    ctx.indent();
                    for b in binds {
                        ctx.push(&b);
                    }
                    for s in &c.body {
                        emit_stmt(ctx, s);
                    }
                    ctx.push("__in_err = 0;");
                    ctx.dedent();
                }
                ctx.line("}"); // last else-if arm
                ctx.dedent();
                ctx.line("}");
            }
            ctx.push("if (!__in_err) { __in_err = __in_err_save; }");
            ctx.dedent();
            ctx.line("}");
        }
        Stmt::Propagate => {
            ctx.push("if (__in_err) {");
            ctx.indent();
            if ctx.ret_is_void {
                ctx.push("return;");
            } else {
                ctx.push("return __in_err_val;");
            }
            ctx.dedent();
            ctx.line("}");
        }
        Stmt::Expr(e) => {
            let v = ctx.expr_str(e);
            ctx.push(&format!("{};", v));
        }
        Stmt::Break => {
            ctx.line("break;");
        }
        Stmt::Continue => {
            ctx.line("continue;");
        }
    }
}

fn is_simple_ident(s: &str) -> bool {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) if c.is_ascii_alphabetic() || c == '_' => {}
        _ => return false,
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
}

/// Returns (C condition, binding statements) for a match arm pattern string.
fn match_arm_cond_and_binds(scrutinee: &str, pattern: &str) -> (String, Vec<String>) {
    let p = pattern.trim().trim_end_matches(':').trim();
    if p == "_" || p == "-" || p == "else" || p == "default" || p == ".." {
        return ("1".into(), vec![]);
    }
    if p == "true" {
        return (format!("({})", scrutinee), vec![]);
    }
    if p == "false" {
        return (format!("(!({}))", scrutinee), vec![]);
    }
    if let Ok(n) = p.parse::<i64>() {
        return (format!("(({}) == INT64_C({}))", scrutinee, n), vec![]);
    }
    if p.len() >= 2 && p.starts_with('"') && p.ends_with('"') {
        let inner = &p[1..p.len() - 1];
        return (
            format!(
                "(({}) == (const char*)\"{}\")",
                scrutinee,
                escape_c_string(inner)
            ),
            vec![],
        );
    }
    // Ident binding: always matches, bind name = scrutinee.
    if is_simple_ident(p) {
        let name = sanitize_ident(p);
        return (
            "1".into(),
            vec![format!("int64_t {} = {};", name, scrutinee)],
        );
    }
    // Struct / other patterns: always true (lossy).
    ("1".into(), vec![])
}

fn collect_loop_bindings(stmts: &[Stmt], locals: &mut Vec<(String, String)>) {
    for stmt in stmts {
        match stmt {
            Stmt::Loop {
                kind: LoopKind::For { binding },
                body,
                ..
            } => {
                let bind = sanitize_ident(binding.trim().trim_start_matches("& "));
                if bind != "_" && !bind.is_empty() && !locals.iter().any(|(n, _)| n == &bind) {
                    locals.push((bind, "int64_t".into()));
                }
                collect_loop_bindings(body, locals);
            }
            Stmt::Loop { body, .. } => collect_loop_bindings(body, locals),
            Stmt::If {
                then_body,
                else_body,
                ..
            } => {
                collect_loop_bindings(then_body, locals);
                collect_loop_bindings(else_body, locals);
            }
            Stmt::Match { arms, .. } => {
                for arm in arms {
                    collect_loop_bindings(&arm.body, locals);
                }
            }
            Stmt::Try { body, catches } => {
                collect_loop_bindings(body, locals);
                for c in catches {
                    collect_loop_bindings(&c.body, locals);
                }
            }
            _ => {}
        }
    }
}

fn collect_locals(stmts: &[Stmt], locals: &mut Vec<(String, String)>) {
    for stmt in stmts {
        match stmt {
            Stmt::Let(name, typ, _) => {
                let n = sanitize_ident(name);
                if !locals.iter().any(|(existing, _)| existing == &n) {
                    let ty = typ.as_ref().map(ctype).unwrap_or_else(|| "int64_t".into());
                    locals.push((n, ty));
                }
            }
            // Some fronts emit bare Assign without a prior Let.
            Stmt::Assign(name, _) => {
                let n = sanitize_ident(name);
                if !locals.iter().any(|(existing, _)| existing == &n) {
                    locals.push((n, "int64_t".into()));
                }
            }
            Stmt::If {
                then_body,
                else_body,
                ..
            } => {
                collect_locals(then_body, locals);
                collect_locals(else_body, locals);
            }
            Stmt::Loop { body, .. } => collect_locals(body, locals),
            Stmt::Match { arms, .. } => {
                for arm in arms {
                    collect_locals(&arm.body, locals);
                }
            }
            Stmt::Try { body, catches } => {
                collect_locals(body, locals);
                for c in catches {
                    collect_locals(&c.body, locals);
                }
            }
            _ => {}
        }
    }
}

#[cfg(test)]
#[path = "c_backend_tests.rs"]
mod tests;
