//! Core IR → AArch64 lowering for the owned native subset.

use crate::core_ir::{Expr, Stmt, Typ, UnifiedModule};
use crate::inrt;
use crate::native_emit::aarch64::{self, CodeEmitter, REG_FP};
use crate::native_emit::macho::{ExportSymbol, MachOLinkage};
use std::cell::RefCell;
use std::collections::HashMap;

thread_local! {
    /// Collector for external symbol references during lowering.
    /// `lower_call` pushes (instruction_offset, symbol_name) when a function
    /// is not in the table and native mode is active.
    pub(crate) static TL_EXTERNAL_REFS: RefCell<Vec<(u32, String)>> = const { RefCell::new(Vec::new()) };
    /// Set true before native binary compilation (false for JIT).
    /// Controls whether unknown functions emit external symbol references
    /// or use dlsym.
    pub(crate) static TL_NATIVE_MODE: RefCell<bool> = const { RefCell::new(false) };
}

mod lower_boundary;
mod lower_call;
mod lower_collect;
mod lower_compile;
mod lower_ctx;
mod lower_expr;
mod lower_iterator;
mod lower_stdlib;
mod lower_stmt;
mod lower_util;

pub use lower_compile::{
    compile_native_artifact, compile_native_artifact_for_host, compile_native_executable,
    compile_native_executable_for_host, host_supports_native_subset,
};

pub(crate) use lower_boundary::boundary_from_module;
pub(crate) use lower_collect::{
    collect_functions, collect_strings, collect_structs, entry_return_kind,
};
pub(crate) use lower_ctx::{
    IteratorMapSlots, LocalSlot, LowerCtx, alloc_declared_locals, append_static_arrays,
    append_string_table,
};
pub(crate) use lower_iterator::lower_vec_for;
pub(crate) use lower_stmt::{lower_stmt, lower_struct_expr_into_regs};
pub(crate) use lower_util::{
    base_struct_name, contains_call, emit_epilogue, emit_failure_return, ensure_return_type,
    expr_type, find_field_offset, is_native_scalar_type, lower_comparison_result,
    native_param_abi_slots, native_struct_fields, pick_scratch, reject_unsupported_function,
};

pub const TARGET_TRIPLE: &str = "aarch64-apple-darwin";

const ENTRY_STUB_SIZE: u32 = 32; // 16 bytes entry stub + 16 bytes global error flag/value

/// Build ARM64 assembly source from lowered code bytes.
/// Each external call site (BL 0 placeholder) is replaced with a proper
/// `bl _symbol` instruction so the assembler+linker resolve it.
fn build_assembly(
    code: &[u8],
    exports: &[(String, u32)],
    external_refs: &[(u32, String)],
    entry: &str,
) -> String {
    // Sort external refs by site for sequential processing
    let mut ext_refs = external_refs.to_vec();
    ext_refs.sort_by_key(|(site, _)| *site);

    let entry_name = native_link_name(entry);
    let mut asm = String::new();
    asm.push_str(".text\n");

    // Build a set of function start positions for labels
    let mut fn_starts: std::collections::HashMap<u32, &str> =
        exports.iter().map(|(n, o)| (*o, n.as_str())).collect();
    // Remove entry and any matching the entry name from fn_starts (we emit them via the entry stub)
    fn_starts.remove(&0);
    // Also remove the entry point function (it's the same symbol)
    fn_starts.retain(|_, name| *name != entry_name);

    // Emit .globl for each exported function
    for (name, _) in exports {
        asm.push_str(&format!(".globl {name}\n"));
    }
    // Emit .globl for external symbols
    let mut seen_ext = std::collections::HashSet::new();
    for (_, name) in &ext_refs {
        if seen_ext.insert(name.clone()) {
            asm.push_str(&format!(".globl {name}\n"));
        }
    }

    // Emit entry point label
    asm.push_str(&format!("{entry_name}:\n"));

    let mut ext_idx = 0usize;
    let mut pos = 0usize;
    while pos < code.len() {
        // Check if this position is a function start → emit label
        if let Some(&fn_name) = fn_starts.get(&(pos as u32)) {
            asm.push_str(&format!("{fn_name}:\n"));
        }

        // Check if this position has an external call
        if ext_idx < ext_refs.len() && (pos as u32) == ext_refs[ext_idx].0 {
            let (_, name) = &ext_refs[ext_idx];
            // Emit the external call as assembly instruction
            // First emit any args setup (the code before BL is setup)
            // The BL is 4 bytes, we replace it with assembly
            asm.push_str(&format!("\tbl\t{name}\n"));
            pos += 4;
            ext_idx += 1;
            continue;
        }

        // Check if this is the entry-point stub area (first ENTRY_STUB_SIZE bytes)
        // The entry stub is generated by inrt — it has a BL to the entry function
        // For now, emit these as raw bytes
        let remaining = code.len() - pos;
        let chunk = if remaining >= 4 { 4 } else { remaining };
        if chunk == 4 {
            let val = u32::from_le_bytes(code[pos..pos + 4].try_into().unwrap());
            asm.push_str(&format!("\t.4byte\t0x{val:08x}\n"));
        } else {
            for i in 0..chunk {
                asm.push_str(&format!("\t.byte\t0x{:02x}\n", code[pos + i]));
            }
        }
        pos += chunk;
    }

    asm
}

/// Map a Rust function name to the linker-visible symbol name.
/// Handles `std::process::exit` → `_exit` (C ABI in libSystem) and
/// `_main` → `_main` (macOS entry convention). For unknown symbols,
/// adds a leading underscore (C ABI convention on macOS).
pub fn native_link_name(name: &str) -> String {
    // Clean up spaces (rust_front may produce "std :: process :: exit" instead of "std::process::exit")
    let cleaned = name.replace(' ', "");
    match cleaned.as_str() {
        "std::process::exit" | "std::process::abort" => "_exit".to_string(),
        "std::io::_print" | "print" => "_printf".to_string(),
        _ => {
            // Replace :: with . for valid assembly symbol names (Mach-O accepts dots).
            // Inlang kebab-case (`make-point`) is not asm-safe; map `-` → `_`.
            // Strip angle-bracket generic params: serde_json.from_str.<BenchMetric> → serde_json.from_str
            let no_generics: String = cleaned.chars().filter(|&c| c != '<' && c != '>').collect();
            // Remove trailing dots
            let trimmed = no_generics.trim_end_matches('.');
            let asm_safe = trimmed.replace("::", ".").replace('-', "_");
            if asm_safe.is_empty() {
                return "_unknown".to_string();
            }
            if asm_safe.starts_with('_') {
                asm_safe
            } else {
                format!("_{}", asm_safe)
            }
        }
    }
}

/// Find the macOS SDK root for the system linker.
fn find_sdk_root() -> Option<String> {
    // Try xcrun --show-sdk-path first
    if let Ok(output) = std::process::Command::new("xcrun")
        .arg("--show-sdk-path")
        .output()
    {
        if output.status.success() {
            if let Ok(path) = String::from_utf8(output.stdout) {
                let trimmed = path.trim().to_string();
                if !trimmed.is_empty() {
                    return Some(trimmed);
                }
            }
        }
    }
    // Fallback: common SDK paths
    for path in &[
        "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk",
    ] {
        if std::path::Path::new(path).exists() {
            return Some(path.to_string());
        }
    }
    None
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum NativeLinkage {
    Executable,
    Dylib,
    StaticLib,
}

impl From<NativeLinkage> for MachOLinkage {
    fn from(linkage: NativeLinkage) -> Self {
        match linkage {
            NativeLinkage::Executable => MachOLinkage::Executable,
            NativeLinkage::Dylib => MachOLinkage::Dylib,
            NativeLinkage::StaticLib => MachOLinkage::StaticLib,
        }
    }
}

#[derive(Debug)]
pub struct LoweredModule {
    pub code: Vec<u8>,
    pub entry_offset: Option<u32>,
    pub exports: Vec<ExportSymbol>,
    /// Function name → byte offset in code (for JIT dispatch)
    pub function_offsets: std::collections::HashMap<String, u32>,
    /// (offset, codegen_base) — absolute address relocations to patch at JIT load time.
    /// Empty for AArch64 (position-independent code).
    pub relocations: Vec<(u32, u64)>,
    /// External symbol names referenced by the code (for native linking).
    /// Each entry is (instruction_offset, symbol_name).
    pub external_refs: Vec<(u32, String)>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum EntryReturn {
    IntLike,
    VoidOrReference,
}

pub(crate) struct PendingCall {
    pub(crate) site: u32,
    pub(crate) target: String,
}

pub(crate) struct PendingInrtCall {
    pub(crate) site: u32,
    pub(crate) target: String,
}

pub(crate) struct PendingStaticArray {
    pub(crate) adr_site: u32,
    pub(crate) values: Vec<i64>,
}

pub(crate) struct PendingString {
    pub(crate) adr_site: u32,
    pub(crate) string_index: i64,
    pub(crate) rd: u8,
}

pub(crate) struct FunctionBuffer {
    pub(crate) name: String,
    pub(crate) bytes: Vec<u8>,
    pub(crate) pending_calls: Vec<PendingCall>,
    pub(crate) pending_inrt_calls: Vec<PendingInrtCall>,
    pub(crate) pending_static_arrays: Vec<PendingStaticArray>,
    pub(crate) pending_strings: Vec<PendingString>,
}

#[derive(Debug, Clone)]
pub(crate) struct FunctionInfo {
    pub(crate) name: String,
    pub(crate) params: Vec<(String, Typ)>,
    pub(crate) ret: Typ,
    pub(crate) body: Vec<Stmt>,
}

fn lower_function_to_buffer(
    func: &FunctionInfo,
    functions: &HashMap<String, FunctionInfo>,
    structs: &HashMap<String, Vec<(String, Typ)>>,
    strings: &HashMap<String, i64>,
) -> Result<FunctionBuffer, String> {
    let mut emitter = CodeEmitter::new();
    let mut pending_calls = Vec::new();
    let mut pending_inrt_calls = Vec::new();
    let mut pending_static_arrays = Vec::new();
    let mut pending_strings = Vec::new();
    lower_function(
        &mut emitter,
        func,
        functions,
        structs,
        strings,
        &mut pending_calls,
        &mut pending_inrt_calls,
        &mut pending_static_arrays,
        &mut pending_strings,
        0,
    )?;
    Ok(FunctionBuffer {
        name: func.name.clone(),
        bytes: emitter.bytes,
        pending_calls,
        pending_inrt_calls,
        pending_static_arrays,
        pending_strings,
    })
}

pub fn lower_module(
    module: &UnifiedModule,
    entry: &str,
    linkage: NativeLinkage,
) -> Result<LoweredModule, String> {
    lower_module_with_jobs(module, entry, linkage, 1)
}

pub fn lower_module_with_jobs(
    module: &UnifiedModule,
    entry: &str,
    linkage: NativeLinkage,
    jobs: usize,
) -> Result<LoweredModule, String> {
    // Clear any stale external refs from previous invocations
    TL_EXTERNAL_REFS.with(|refs| refs.borrow_mut().clear());
    let functions = collect_functions(module)?;
    let structs = collect_structs(module);
    let strings = collect_strings(module);
    // Try exact match first, then namespaced variants
    let resolved_entry = if functions.contains_key(entry) {
        entry.to_string()
    } else {
        // Try any function ending with .<entry> (namespaced)
        functions
            .keys()
            .find(|k| k.ends_with(&format!(".{entry}")))
            .cloned()
            .or_else(|| functions.keys().find(|k| k.as_str() == entry).cloned())
            .unwrap_or_else(|| {
                // Entry not found — pick first non-closure function as fallback.
                // This lets library crates without main lower all functions.
                functions
                    .keys()
                    .find(|k| !k.starts_with("__closure_"))
                    .cloned()
                    .unwrap_or_else(|| entry.to_string())
            })
    };
    let entry_return = functions
        .get(&resolved_entry)
        .map(|func| entry_return_kind(&func.ret))
        .unwrap_or(EntryReturn::VoidOrReference);

    let mut emitter = CodeEmitter::new();
    emitter.bytes.resize(ENTRY_STUB_SIZE as usize, 0);
    let mut function_offsets = HashMap::new();
    let mut pending_inrt_calls = Vec::new();
    let mut pending_static_arrays = Vec::new();
    let mut pending_strings = Vec::new();
    let mut names: Vec<String> = functions.keys().cloned().collect();
    names.retain(|name| !name.starts_with("__closure_"));
    names.sort();

    // Lower each function. Failures are skipped; callers get return-0 stubs.
    // ponytail: graceful degradation for self-hosting — skip stdlib functions
    // that use unsupported types rather than failing the entire module.
    let jobs = jobs.max(1);
    let (buffers, skipped): (Vec<FunctionBuffer>, Vec<(String, String)>) =
        if jobs == 1 || names.len() <= 1 {
            let mut bufs = Vec::with_capacity(names.len());
            let mut skip = Vec::new();
            for name in &names {
                let func = &functions[name];
                match lower_function_to_buffer(func, &functions, &structs, &strings) {
                    Ok(buf) => bufs.push(buf),
                    Err(e) => {
                        skip.push((name.clone(), e));
                    }
                }
            }
            (bufs, skip)
        } else {
            std::thread::scope(|s| {
                let functions = &functions;
                let structs = &structs;
                let strings = &strings;
                let chunks: Vec<Vec<String>> = names
                    .chunks(names.len().div_ceil(jobs))
                    .map(|c| c.to_vec())
                    .collect();
                let mut handles = Vec::with_capacity(chunks.len());
                for chunk in chunks {
                    handles.push(s.spawn(move || {
                        let mut bufs = Vec::new();
                        let mut skips = Vec::new();
                        for name in chunk {
                            let func = &functions[&name];
                            match lower_function_to_buffer(func, functions, structs, strings) {
                                Ok(buf) => bufs.push((name, buf)),
                                Err(e) => {
                                    skips.push((name, e));
                                }
                            }
                        }
                        (bufs, skips)
                    }));
                }
                let mut results: Vec<(String, FunctionBuffer)> = Vec::with_capacity(names.len());
                let mut skip = Vec::new();
                for h in handles {
                    let (bufs, skips) = h
                        .join()
                        .map_err(|e| format!("native-lower: worker thread panicked: {e:?}"))?;
                    results.extend(bufs);
                    skip.extend(skips);
                }
                results.sort_by(|(a, _), (b, _)| a.cmp(b));
                let buffers: Vec<FunctionBuffer> = results.into_iter().map(|(_, b)| b).collect();
                Ok::<_, String>((buffers, skip))
            })?
        };

    // Summarize skipped functions: only print individual skips in debug.
    // In release mode, print a single summary line to avoid log noise.
    if !skipped.is_empty() {
        #[cfg(debug_assertions)]
        for (name, err) in &skipped {
            eprintln!("native-lower: skipping `{name}`: {err}");
        }
        eprintln!(
            "native-lower: {} functions lowered, {} skipped (unsupported types/calls)",
            buffers.len(),
            skipped.len()
        );
    }
    // Each stub: MOV X0, #0; RET — returns 0 for any call.
    // But if the entry function itself was skipped, fail the entire module.
    if let Some((_, err)) = skipped.iter().find(|(name, _)| name == &resolved_entry) {
        return Err(format!(
            "native-lower: entry function `{resolved_entry}` unsupported: {err}"
        ));
    }
    for (name, _) in &skipped {
        let offset = emitter.len();
        function_offsets.insert(name.clone(), offset);
        emitter.emit_insns(&aarch64::load_i64(0, 0));
        emitter.emit_u32(aarch64::ret());
    }

    // Append all per-function buffers and record global offsets.
    for buf in &buffers {
        let offset = emitter.len();
        function_offsets.insert(buf.name.clone(), offset);
        emitter.bytes.extend_from_slice(&buf.bytes);
    }

    // Patch internal function calls (BL) using global offsets.
    // ponytail: calls to skipped/unresolved targets get a return-0 stub
    // rather than failing the entire module.
    for buf in &buffers {
        let base = *function_offsets
            .get(&buf.name)
            .ok_or_else(|| format!("native-lower: missing function offset for `{}`", buf.name))?;
        for call in &buf.pending_calls {
            let target_offset = function_offsets.get(&call.target).copied();
            let target_offset = match target_offset {
                Some(o) => o,
                None => {
                    // Emit a stub for this unresolved target.
                    let stub_offset = emitter.len();
                    function_offsets.insert(call.target.clone(), stub_offset);
                    emitter.emit_insns(&aarch64::load_i64(0, 0));
                    emitter.emit_u32(aarch64::ret());
                    eprintln!(
                        "native-lower: stubbed unresolved call target `{}`",
                        call.target
                    );
                    stub_offset
                }
            };
            let global_site = base + call.site;
            let rel = target_offset as i32 - global_site as i32;
            emitter.patch_u32(global_site, aarch64::bl(rel));
        }
    }

    // Collect pending static arrays, strings, and inrt calls from all buffers,
    // translating local sites to global offsets.
    for buf in buffers {
        let base = *function_offsets
            .get(&buf.name)
            .ok_or_else(|| format!("native-lower: missing function offset for `{}`", buf.name))?;
        pending_static_arrays.extend(buf.pending_static_arrays.into_iter().map(|a| {
            PendingStaticArray {
                adr_site: base + a.adr_site,
                values: a.values,
            }
        }));
        pending_strings.extend(buf.pending_strings.into_iter().map(|p| PendingString {
            adr_site: base + p.adr_site,
            string_index: p.string_index,
            rd: p.rd,
        }));
        pending_inrt_calls.extend(buf.pending_inrt_calls.into_iter().map(|c| PendingInrtCall {
            site: base + c.site,
            target: c.target,
        }));
    }

    append_static_arrays(&mut emitter, pending_static_arrays);
    append_string_table(&mut emitter, &strings, pending_strings);

    if !pending_inrt_calls.is_empty() {
        let (runtime_blob, runtime_offsets) = inrt::build_runtime_blob();
        let runtime_base = emitter.len();
        emitter.bytes.extend_from_slice(&runtime_blob);
        for call in &pending_inrt_calls {
            let fn_offset = *runtime_offsets.get(call.target.as_str()).ok_or_else(|| {
                format!(
                    "native-lower: unresolved inrt call target `{}`",
                    call.target
                )
            })?;
            let target_abs = runtime_base + fn_offset;
            let offset = target_abs as i32 - call.site as i32;
            emitter.patch_u32(call.site, aarch64::bl(offset));
        }
    }

    let entry_offset = if linkage == NativeLinkage::Executable {
        let entry_fn_offset = *function_offsets
            .get(&resolved_entry)
            .ok_or_else(|| format!("native-lower: missing entry function `{resolved_entry}`"))?;
        let stub = match entry_return {
            EntryReturn::IntLike => inrt::build_entry_stub(entry_fn_offset),
            EntryReturn::VoidOrReference => {
                inrt::build_entry_stub_with_forced_exit(entry_fn_offset, 0)
            }
        };
        emitter.bytes[..stub.len()].copy_from_slice(&stub);
        Some(0)
    } else {
        None
    };

    let mut export_names: Vec<String> = function_offsets.keys().cloned().collect();
    export_names.sort();
    let exports: Vec<ExportSymbol> = export_names
        .into_iter()
        .map(|name| {
            let offset = *function_offsets
                .get(&name)
                .ok_or_else(|| format!("native-lower: missing export offset for `{}`", name))?;
            Ok(ExportSymbol {
                name: name.clone(),
                offset,
            })
        })
        .collect::<Result<_, String>>()?;

    let external_refs = TL_EXTERNAL_REFS.with(|refs| std::mem::take(&mut *refs.borrow_mut()));
    Ok(LoweredModule {
        code: emitter.bytes,
        entry_offset,
        exports,
        function_offsets,
        relocations: Vec::new(), // AArch64 uses position-independent code
        external_refs,
    })
}

fn lower_function(
    emitter: &mut CodeEmitter,
    func: &FunctionInfo,
    functions: &HashMap<String, FunctionInfo>,
    structs: &HashMap<String, Vec<(String, Typ)>>,
    strings: &HashMap<String, i64>,
    pending_calls: &mut Vec<PendingCall>,
    pending_inrt_calls: &mut Vec<PendingInrtCall>,
    pending_static_arrays: &mut Vec<PendingStaticArray>,
    pending_strings: &mut Vec<PendingString>,
    _fn_start_offset: u32,
) -> Result<(), String> {
    ensure_return_type(&func.ret, &func.name, structs)?;
    reject_unsupported_function(func, structs)?;

    emitter.emit_u32(0xA9BF_7BFD);
    emitter.emit_u32(aarch64::mov_reg64(REG_FP, aarch64::REG_SP));
    // X27 set by JIT caller to error page address (throw/try/catch).

    let mut ctx = LowerCtx::new(
        &func.params,
        structs,
        strings,
        pending_static_arrays,
        pending_inrt_calls,
        pending_strings,
        &func.name,
    )?;
    alloc_declared_locals(&mut ctx, &func.body, &func.name, functions)?;
    ctx.binop_temp = ctx.alloc_slot();
    for index in 0..ctx.binop_temps.len() {
        ctx.binop_temps[index] = ctx.alloc_slot();
    }
    ctx.saved_flag_offset = ctx.stack_size + 8;
    ctx.stack_size += 16;
    for index in 0..ctx.call_arg_temps.len() {
        ctx.call_arg_temps[index] = ctx.alloc_slot();
    }
    let aggregate_vector_words =
        max_aggregate_vector_literal_words(&func.body, structs, &func.name)?;
    if has_struct_return_vec_literal(&func.body)
        || aggregate_vector_words.is_some()
        || has_iter_once(&func.body)
        || has_iter_map(&func.body)
    {
        ctx.vec_literal_header_offset = Some(ctx.alloc_slot());
        ctx.alloc_slot();
        ctx.alloc_slot();
    }
    if has_iter_chain(&func.body) {
        ctx.iterator_chain_header_offset = Some(ctx.alloc_slot());
        ctx.alloc_slot();
        ctx.alloc_slot();
    }
    if has_iter_map(&func.body) {
        ctx.iterator_map_slots = Some(IteratorMapSlots {
            ptr: ctx.alloc_slot(),
            len: ctx.alloc_slot(),
            index: ctx.alloc_slot(),
            binding: ctx.alloc_slot(),
        });
    }
    if let Some(words) = aggregate_vector_words {
        let offset = ctx.alloc_slot();
        for _ in 1..words {
            ctx.alloc_slot();
        }
        ctx.aggregate_vector_scratch = Some((offset, words));
    }
    if ctx.stack_size > 0 {
        emitter.emit_u32(aarch64::sub_imm64(
            aarch64::REG_SP,
            aarch64::REG_SP,
            ctx.stack_reserve() as u16,
        ));
    }
    ctx.prologue_stack_reserve = ctx.stack_reserve();
    for (reg, offset) in &ctx.param_stores {
        emitter.emit_u32(aarch64::str64(*reg, aarch64::REG_SP, *offset));
    }
    // ponytail: for &self parameters, the register holds a pointer, not field value.
    // Dereference the stored pointer to load actual field values into the slots.
    // Load the pointer ONCE into x15, then use it for all field loads.
    for (name, typ) in &func.params {
        if let Typ::Named(struct_name) = typ {
            if name == "self" || name.starts_with("self:") {
                if let Some(LocalSlot::Struct {
                    fields: field_map, ..
                }) = ctx.locals.get(name)
                {
                    let pointer_slot = ctx.param_stores.iter().find_map(|(_, off)| {
                        if field_map.values().any(|v| v == off) {
                            Some(*off)
                        } else {
                            None
                        }
                    });
                    if let Some(ptr_slot) = pointer_slot {
                        emitter.emit_u32(aarch64::ldr64(15, aarch64::REG_SP, ptr_slot));
                        let schema = native_struct_fields(structs, struct_name, &func.name)
                            .unwrap_or_default();
                        for (i, (field, _)) in schema.iter().enumerate() {
                            if let Some(&off) = find_field_offset(field_map, field) {
                                emitter.emit_u32(aarch64::ldr64(14, 15, (i * 8) as u32));
                                emitter.emit_u32(aarch64::str64(14, aarch64::REG_SP, off));
                            }
                        }
                    }
                }
            }
        }
    }
    // Load stack-based params (>8) from caller's stack area
    let stack_base = ctx.stack_reserve() + 16;
    for (arg_idx, local_off) in &ctx.stack_params {
        let incoming_off = stack_base + 8 * arg_idx;
        emitter.emit_u32(aarch64::ldr64(15, aarch64::REG_SP, incoming_off));
        emitter.emit_u32(aarch64::str64(15, aarch64::REG_SP, *local_off));
    }
    // Handle implicit return: last stmt is an Expr with multi-field struct init
    let last_is_struct_init = func
        .body
        .last()
        .map_or(false, |s| matches!(s, Stmt::Expr(Expr::StructInit { .. })));
    if last_is_struct_init {
        let last = func.body.last().unwrap();
        let (init_name, init_fields) = match last {
            Stmt::Expr(Expr::StructInit { name, fields }) => (name.clone(), fields.clone()),
            _ => return Err("native-lower: expected StructInit as last statement".to_string()),
        };
        for stmt in &func.body[..func.body.len() - 1] {
            lower_stmt(
                emitter,
                &mut ctx,
                stmt,
                functions,
                pending_calls,
                &func.name,
                &func.ret,
            )?;
        }
        let ret_name = match &func.ret {
            Typ::Named(n) => n.clone(),
            _ => init_name.clone(),
        };
        lower_struct_expr_into_regs(
            emitter,
            &mut ctx,
            &Expr::StructInit {
                name: init_name,
                fields: init_fields,
            },
            &ret_name,
            functions,
            pending_calls,
            &func.name,
        )?;
    } else {
        for stmt in &func.body {
            lower_stmt(
                emitter,
                &mut ctx,
                stmt,
                functions,
                pending_calls,
                &func.name,
                &func.ret,
            )?;
        }
    }
    ctx.assert_vec_for_slots_consumed(&func.name)?;

    if !ctx.emitted_return {
        if func.ret == Typ::Void {
            emitter.emit_insns(&aarch64::load_i64(0, 0));
        }
        emit_epilogue(emitter, ctx.prologue_stack_reserve);
    }

    Ok(())
}

fn has_iter_once(body: &[Stmt]) -> bool {
    fn expr_has_once(expr: &Expr) -> bool {
        match expr {
            Expr::Call { callee, args, .. } => {
                matches!(callee.as_ref(), Expr::Ident(name) if name == "std::iter::once")
                    || expr_has_once(callee)
                    || args.iter().any(expr_has_once)
            }
            Expr::Binary { lhs, rhs, .. } => expr_has_once(lhs) || expr_has_once(rhs),
            Expr::Unary { expr, .. } | Expr::Field { base: expr, .. } => expr_has_once(expr),
            Expr::Index { base, index } => expr_has_once(base) || expr_has_once(index),
            Expr::StructInit { fields, .. } => fields.iter().any(|(_, value)| expr_has_once(value)),
            Expr::ArrayLit(items) => items.iter().any(expr_has_once),
            Expr::IntLit(_)
            | Expr::FloatLit(_)
            | Expr::StringLit(_)
            | Expr::BoolLit(_)
            | Expr::Ident(_)
            | Expr::Closure { .. } => false,
        }
    }
    body.iter().any(|stmt| match stmt {
        Stmt::Let(_, _, expr)
        | Stmt::Assign(_, expr)
        | Stmt::Expr(expr)
        | Stmt::Return(Some(expr))
        | Stmt::Throw(expr) => expr_has_once(expr),
        Stmt::IndexAssign {
            base, index, value, ..
        } => expr_has_once(base) || expr_has_once(index) || expr_has_once(value),
        Stmt::FieldAssign { base, value, .. } => expr_has_once(base) || expr_has_once(value),
        Stmt::If {
            cond,
            then_body,
            else_body,
        } => expr_has_once(cond) || has_iter_once(then_body) || has_iter_once(else_body),
        Stmt::Loop { cond, body, .. } => {
            cond.as_ref().is_some_and(expr_has_once) || has_iter_once(body)
        }
        Stmt::Match {
            scrutinee, arms, ..
        } => expr_has_once(scrutinee) || arms.iter().any(|arm| has_iter_once(&arm.body)),
        Stmt::Try { body, catches, .. } => {
            has_iter_once(body) || catches.iter().any(|catch| has_iter_once(&catch.body))
        }
        Stmt::Return(None) | Stmt::Break | Stmt::Propagate => false,
    })
}

fn has_iter_map(body: &[Stmt]) -> bool {
    fn expr_has_map(expr: &Expr) -> bool {
        match expr {
            Expr::Call { callee, args, .. } => {
                matches!(callee.as_ref(), Expr::Ident(name) if name == "map")
                    || expr_has_map(callee)
                    || args.iter().any(expr_has_map)
            }
            Expr::Binary { lhs, rhs, .. } => expr_has_map(lhs) || expr_has_map(rhs),
            Expr::Unary { expr, .. } | Expr::Field { base: expr, .. } => expr_has_map(expr),
            Expr::Index { base, index } => expr_has_map(base) || expr_has_map(index),
            Expr::StructInit { fields, .. } => fields.iter().any(|(_, value)| expr_has_map(value)),
            Expr::ArrayLit(items) => items.iter().any(expr_has_map),
            Expr::Closure { body, .. } => has_iter_map(body),
            Expr::IntLit(_)
            | Expr::FloatLit(_)
            | Expr::StringLit(_)
            | Expr::BoolLit(_)
            | Expr::Ident(_) => false,
        }
    }
    body.iter().any(|stmt| match stmt {
        Stmt::Let(_, _, expr)
        | Stmt::Assign(_, expr)
        | Stmt::Expr(expr)
        | Stmt::Return(Some(expr))
        | Stmt::Throw(expr) => expr_has_map(expr),
        Stmt::IndexAssign {
            base, index, value, ..
        } => expr_has_map(base) || expr_has_map(index) || expr_has_map(value),
        Stmt::FieldAssign { base, value, .. } => expr_has_map(base) || expr_has_map(value),
        Stmt::If {
            cond,
            then_body,
            else_body,
        } => expr_has_map(cond) || has_iter_map(then_body) || has_iter_map(else_body),
        Stmt::Loop { cond, body, .. } => {
            cond.as_ref().is_some_and(expr_has_map) || has_iter_map(body)
        }
        Stmt::Match {
            scrutinee, arms, ..
        } => expr_has_map(scrutinee) || arms.iter().any(|arm| has_iter_map(&arm.body)),
        Stmt::Try { body, catches, .. } => {
            has_iter_map(body) || catches.iter().any(|catch| has_iter_map(&catch.body))
        }
        Stmt::Return(None) | Stmt::Break | Stmt::Propagate => false,
    })
}

fn has_iter_chain(body: &[Stmt]) -> bool {
    fn expr_has_chain(expr: &Expr) -> bool {
        match expr {
            Expr::Call { callee, args, .. } => {
                matches!(callee.as_ref(), Expr::Ident(name) if name == "chain")
                    || expr_has_chain(callee)
                    || args.iter().any(expr_has_chain)
            }
            Expr::Binary { lhs, rhs, .. } => expr_has_chain(lhs) || expr_has_chain(rhs),
            Expr::Unary { expr, .. } | Expr::Field { base: expr, .. } => expr_has_chain(expr),
            Expr::Index { base, index } => expr_has_chain(base) || expr_has_chain(index),
            Expr::StructInit { fields, .. } => {
                fields.iter().any(|(_, value)| expr_has_chain(value))
            }
            Expr::ArrayLit(items) => items.iter().any(expr_has_chain),
            Expr::IntLit(_)
            | Expr::FloatLit(_)
            | Expr::StringLit(_)
            | Expr::BoolLit(_)
            | Expr::Ident(_)
            | Expr::Closure { .. } => false,
        }
    }
    body.iter().any(|stmt| match stmt {
        Stmt::Let(_, _, expr)
        | Stmt::Assign(_, expr)
        | Stmt::Expr(expr)
        | Stmt::Return(Some(expr))
        | Stmt::Throw(expr) => expr_has_chain(expr),
        Stmt::If {
            cond,
            then_body,
            else_body,
        } => expr_has_chain(cond) || has_iter_chain(then_body) || has_iter_chain(else_body),
        Stmt::Loop { cond, body, .. } => {
            cond.as_ref().is_some_and(expr_has_chain) || has_iter_chain(body)
        }
        Stmt::Match {
            scrutinee, arms, ..
        } => expr_has_chain(scrutinee) || arms.iter().any(|arm| has_iter_chain(&arm.body)),
        Stmt::Try { body, catches, .. } => {
            has_iter_chain(body) || catches.iter().any(|catch| has_iter_chain(&catch.body))
        }
        Stmt::IndexAssign {
            base, index, value, ..
        } => expr_has_chain(base) || expr_has_chain(index) || expr_has_chain(value),
        Stmt::FieldAssign { base, value, .. } => expr_has_chain(base) || expr_has_chain(value),
        Stmt::Return(None) | Stmt::Break | Stmt::Propagate => false,
    })
}

fn has_struct_return_vec_literal(body: &[Stmt]) -> bool {
    body.iter().any(|stmt| match stmt {
        Stmt::Return(Some(Expr::StructInit { fields, .. })) => fields
            .iter()
            .any(|(_, value)| matches!(value, Expr::ArrayLit(_))),
        Stmt::If {
            then_body,
            else_body,
            ..
        } => has_struct_return_vec_literal(then_body) || has_struct_return_vec_literal(else_body),
        Stmt::Loop { body, .. } | Stmt::Try { body, .. } => has_struct_return_vec_literal(body),
        Stmt::Match { arms, .. } => arms
            .iter()
            .any(|arm| has_struct_return_vec_literal(&arm.body)),
        _ => false,
    })
}

fn max_aggregate_vector_literal_words(
    body: &[Stmt],
    structs: &HashMap<String, Vec<(String, Typ)>>,
    fn_name: &str,
) -> Result<Option<usize>, String> {
    fn max_nested_vector_element_words(
        typ: &Typ,
        structs: &HashMap<String, Vec<(String, Typ)>>,
        fn_name: &str,
        visited: &mut Vec<String>,
        depth: u32,
    ) -> Result<usize, String> {
        if depth > 40 {
            return Ok(0);
        }
        match typ {
            Typ::Vector(element) => {
                let mut max = lower_util::native_param_abi_slots(
                    &[("value".to_string(), (**element).clone())],
                    structs,
                    fn_name,
                )?;
                max = max.max(max_nested_vector_element_words(
                    element,
                    structs,
                    fn_name,
                    visited,
                    depth + 1,
                )?);
                Ok(max)
            }
            Typ::Named(name) => {
                let base = base_struct_name(name);
                if visited.iter().any(|v| v == base) {
                    return Ok(0);
                }
                visited.push(base.to_string());
                let fields = lower_util::native_struct_fields(structs, name, fn_name)?;
                let mut max = 0;
                for (_, field_typ) in fields {
                    max = max.max(max_nested_vector_element_words(
                        &field_typ,
                        structs,
                        fn_name,
                        visited,
                        depth + 1,
                    )?);
                }
                visited.pop();
                Ok(max)
            }
            Typ::Array(element) => {
                max_nested_vector_element_words(element, structs, fn_name, visited, depth + 1)
            }
            _ => Ok(0),
        }
    }
    fn inspect_expr(
        expr: &Expr,
        structs: &HashMap<String, Vec<(String, Typ)>>,
        fn_name: &str,
        max: &mut usize,
    ) -> Result<(), String> {
        match expr {
            Expr::ArrayLit(items) => {
                if let Some(Expr::StructInit { name, .. }) = items.first() {
                    let words = lower_util::native_param_abi_slots(
                        &[("value".to_string(), Typ::Named(name.clone()))],
                        structs,
                        fn_name,
                    )?;
                    *max = (*max).max(words);
                    let mut visited = Vec::new();
                    *max = (*max).max(max_nested_vector_element_words(
                        &Typ::Named(name.clone()),
                        structs,
                        fn_name,
                        &mut visited,
                        0,
                    )?);
                }
                for item in items {
                    inspect_expr(item, structs, fn_name, max)?;
                }
            }
            Expr::Binary { lhs, rhs, .. } => {
                inspect_expr(lhs, structs, fn_name, max)?;
                inspect_expr(rhs, structs, fn_name, max)?;
            }
            Expr::Unary { expr, .. } | Expr::Field { base: expr, .. } => {
                inspect_expr(expr, structs, fn_name, max)?;
            }
            Expr::Index { base, index } => {
                inspect_expr(base, structs, fn_name, max)?;
                inspect_expr(index, structs, fn_name, max)?;
            }
            Expr::Call { callee, args, .. } => {
                inspect_expr(callee, structs, fn_name, max)?;
                for arg in args {
                    inspect_expr(arg, structs, fn_name, max)?;
                }
            }
            Expr::StructInit { fields, .. } => {
                for (_, value) in fields {
                    inspect_expr(value, structs, fn_name, max)?;
                }
            }
            Expr::Closure { body, .. } => {
                for stmt in body {
                    if let Stmt::Return(Some(Expr::StructInit { name, .. })) = stmt {
                        let words = lower_util::native_param_abi_slots(
                            &[("value".to_string(), Typ::Named(name.clone()))],
                            structs,
                            fn_name,
                        )?;
                        *max = (*max).max(words);
                        let mut visited = Vec::new();
                        *max = (*max).max(max_nested_vector_element_words(
                            &Typ::Named(name.clone()),
                            structs,
                            fn_name,
                            &mut visited,
                            0,
                        )?);
                    }
                }
                inspect_body(body, structs, fn_name, max)?;
            }
            Expr::IntLit(_)
            | Expr::FloatLit(_)
            | Expr::StringLit(_)
            | Expr::BoolLit(_)
            | Expr::Ident(_) => {}
        }
        Ok(())
    }
    fn inspect_body(
        body: &[Stmt],
        structs: &HashMap<String, Vec<(String, Typ)>>,
        fn_name: &str,
        max: &mut usize,
    ) -> Result<(), String> {
        for stmt in body {
            match stmt {
                Stmt::Let(_, _, expr)
                | Stmt::Assign(_, expr)
                | Stmt::Expr(expr)
                | Stmt::Return(Some(expr))
                | Stmt::Throw(expr) => inspect_expr(expr, structs, fn_name, max)?,
                Stmt::IndexAssign {
                    base, index, value, ..
                } => {
                    inspect_expr(base, structs, fn_name, max)?;
                    inspect_expr(index, structs, fn_name, max)?;
                    inspect_expr(value, structs, fn_name, max)?;
                }
                Stmt::FieldAssign { base, value, .. } => {
                    inspect_expr(base, structs, fn_name, max)?;
                    inspect_expr(value, structs, fn_name, max)?;
                }
                Stmt::If {
                    cond,
                    then_body,
                    else_body,
                } => {
                    inspect_expr(cond, structs, fn_name, max)?;
                    inspect_body(then_body, structs, fn_name, max)?;
                    inspect_body(else_body, structs, fn_name, max)?;
                }
                Stmt::Loop { cond, body, .. } => {
                    if let Some(cond) = cond {
                        inspect_expr(cond, structs, fn_name, max)?;
                    }
                    inspect_body(body, structs, fn_name, max)?;
                }
                Stmt::Match {
                    scrutinee, arms, ..
                } => {
                    inspect_expr(scrutinee, structs, fn_name, max)?;
                    for arm in arms {
                        inspect_body(&arm.body, structs, fn_name, max)?;
                    }
                }
                Stmt::Try { body, catches, .. } => {
                    inspect_body(body, structs, fn_name, max)?;
                    for catch in catches {
                        inspect_body(&catch.body, structs, fn_name, max)?;
                    }
                }
                Stmt::Return(None) | Stmt::Break | Stmt::Propagate => {}
            }
        }
        Ok(())
    }
    let mut max = 0;
    inspect_body(body, structs, fn_name, &mut max)?;
    Ok((max != 0).then_some(max))
}

#[cfg(test)]
mod lower_tests;
