//! Core IR → high-level source sinks (Go, Rust).
//! Lossy subset printers — not project/crate generators.

use crate::core_ir::{Decl, Expr, LoopKind, Stmt, Typ, UnifiedModule};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SourceLang {
    Go,
    Rust,
}

const MAX_EMIT_DEPTH: u32 = 256;
const MAX_EMIT_NODES: usize = 100_000;

pub fn emit_source_module(module: &UnifiedModule, lang: SourceLang) -> String {
    // Soft DoS guard: truncate emission rather than hang (lossy printers).
    if !module_within_limits(module) {
        return format!("// emit aborted: Core IR exceeds size/depth limits\n// lang={lang:?}\n");
    }
    let mut out = String::with_capacity(4096);
    match lang {
        SourceLang::Go => {
            out.push_str("// Generated by Inauguration source backend (Go)\npackage main\n\n")
        }
        SourceLang::Rust => out.push_str("// Generated by Inauguration source backend (Rust)\n\n"),
    }
    if let Some(pkg) = &module.identity.package {
        out.push_str(&format!("// package: {}\n", sanitize_line(pkg)));
    }
    if let Some(m) = &module.identity.module {
        out.push_str(&format!("// module: {}\n", sanitize_line(m)));
    }
    if module.identity.package.is_some() || module.identity.module.is_some() {
        out.push('\n');
    }
    for decl in &module.decls {
        emit_decl(&mut out, lang, decl);
    }
    out
}

fn emit_decl(out: &mut String, lang: SourceLang, decl: &Decl) {
    match decl {
        Decl::Struct { name, fields, .. } => emit_struct(out, lang, name, fields),
        Decl::Class {
            name,
            fields,
            methods,
            ..
        } => {
            emit_struct(out, lang, name, fields);
            if lang == SourceLang::Rust {
                out.push_str(&format!("impl {} {{\n", sanitize(name)));
            }
            for m in methods {
                if let Decl::Function {
                    name: mname,
                    params,
                    ret,
                    body,
                    ..
                } = m
                {
                    emit_fn(out, lang, Some(name), mname, params, ret, body);
                }
            }
            if lang == SourceLang::Rust {
                out.push_str("}\n\n");
            }
        }
        Decl::Function {
            name,
            params,
            ret,
            body,
            ..
        } => emit_fn(out, lang, None, name, params, ret, body),
        Decl::Global {
            name, typ, init, ..
        } => {
            let init_s = init
                .as_ref()
                .map(|e| format!(" = {}", expr(lang, e)))
                .unwrap_or_default();
            match lang {
                SourceLang::Go => out.push_str(&format!(
                    "var {} {}{}\n",
                    sanitize(name),
                    type_str(lang, typ),
                    init_s
                )),
                SourceLang::Rust => out.push_str(&format!(
                    "static {}: {}{};\n",
                    sanitize(name),
                    type_str(lang, typ),
                    init_s
                )),
            }
        }
        Decl::Interface { name, methods, .. } => match lang {
            SourceLang::Go => {
                out.push_str(&format!("type {} interface {{\n", sanitize(name)));
                for m in methods {
                    let ps = params_go(&m.params);
                    let r = type_str(lang, &m.ret);
                    if r.is_empty() {
                        out.push_str(&format!("\t{}({})\n", export_go(&m.name), ps));
                    } else {
                        out.push_str(&format!("\t{}({}) {}\n", export_go(&m.name), ps, r));
                    }
                }
                out.push_str("}\n\n");
            }
            SourceLang::Rust => {
                out.push_str(&format!("trait {} {{\n", sanitize(name)));
                for m in methods {
                    out.push_str(&format!(
                        "    fn {}({}) -> {};\n",
                        sanitize(&m.name),
                        params_rust(&m.params),
                        type_str(lang, &m.ret)
                    ));
                }
                out.push_str("}\n\n");
            }
        },
        Decl::Component { name, target, .. } => {
            out.push_str(&format!("// component {name} target={target}\n"));
        }
    }
}

fn emit_struct(out: &mut String, lang: SourceLang, name: &str, fields: &[(String, Typ)]) {
    match lang {
        SourceLang::Go => {
            out.push_str(&format!("type {} struct {{\n", sanitize(name)));
            for (fname, ftype) in fields {
                out.push_str(&format!(
                    "\t{} {}\n",
                    export_go(fname),
                    type_str(lang, ftype)
                ));
            }
            out.push_str("}\n\n");
        }
        SourceLang::Rust => {
            out.push_str(&format!("struct {} {{\n", sanitize(name)));
            for (fname, ftype) in fields {
                out.push_str(&format!(
                    "    {}: {},\n",
                    sanitize(fname),
                    type_str(lang, ftype)
                ));
            }
            out.push_str("}\n\n");
        }
    }
}

fn emit_fn(
    out: &mut String,
    lang: SourceLang,
    recv: Option<&str>,
    name: &str,
    params: &[(String, Typ)],
    ret: &Typ,
    body: &[Stmt],
) {
    match lang {
        SourceLang::Go => {
            let r = type_str(lang, ret);
            let ps = params_go(params);
            if let Some(rt) = recv {
                if r.is_empty() {
                    out.push_str(&format!(
                        "func (self *{}) {}({}) {{\n",
                        sanitize(rt),
                        export_go(name),
                        ps
                    ));
                } else {
                    out.push_str(&format!(
                        "func (self *{}) {}({}) {} {{\n",
                        sanitize(rt),
                        export_go(name),
                        ps,
                        r
                    ));
                }
            } else if r.is_empty() || name == "main" {
                out.push_str(&format!("func {}({}) {{\n", sanitize(name), ps));
            } else {
                out.push_str(&format!("func {}({}) {} {{\n", sanitize(name), ps, r));
            }
            for s in body {
                stmt(out, lang, s, 1);
            }
            out.push_str("}\n\n");
        }
        SourceLang::Rust => {
            let indent = if recv.is_some() { "    " } else { "" };
            let ps = if recv.is_some() {
                let rest = params_rust(params);
                if rest.is_empty() {
                    "&mut self".into()
                } else {
                    format!("&mut self, {rest}")
                }
            } else {
                params_rust(params)
            };
            out.push_str(&format!(
                "{indent}fn {}({}) -> {} {{\n",
                sanitize(name),
                ps,
                type_str(lang, ret)
            ));
            for s in body {
                stmt(out, lang, s, if recv.is_some() { 2 } else { 1 });
            }
            out.push_str(&format!("{indent}}}\n\n"));
        }
    }
}

fn type_str(lang: SourceLang, typ: &Typ) -> String {
    match (lang, typ.canonical()) {
        (SourceLang::Go, Typ::Int) => "int64".into(),
        (SourceLang::Go, Typ::Bool) => "bool".into(),
        (SourceLang::Go, Typ::Float) => "float64".into(),
        (SourceLang::Go, Typ::String) => "string".into(),
        (SourceLang::Go, Typ::Void) => "".into(),
        (SourceLang::Go, Typ::Array(inner) | Typ::Vector(inner)) => {
            format!("[]{}", type_str(lang, &inner))
        }
        (SourceLang::Go, Typ::Named(n)) if n == "Vec" || n == "InVec" => "[]int64".into(),
        (SourceLang::Go, Typ::Named(n) | Typ::Generic(n)) => sanitize(&n),

        (SourceLang::Rust, Typ::Int) => "i64".into(),
        (SourceLang::Rust, Typ::Bool) => "bool".into(),
        (SourceLang::Rust, Typ::Float) => "f64".into(),
        (SourceLang::Rust, Typ::String) => "String".into(),
        (SourceLang::Rust, Typ::Void) => "()".into(),
        (SourceLang::Rust, Typ::Array(inner) | Typ::Vector(inner)) => {
            format!("Vec<{}>", type_str(lang, &inner))
        }
        (SourceLang::Rust, Typ::Named(n)) if n == "Vec" || n == "InVec" => "Vec<i64>".into(),
        (SourceLang::Rust, Typ::Named(n) | Typ::Generic(n)) => sanitize(&n),
    }
}

fn params_go(params: &[(String, Typ)]) -> String {
    params
        .iter()
        .map(|(n, t)| format!("{} {}", sanitize(n), type_str(SourceLang::Go, t)))
        .collect::<Vec<_>>()
        .join(", ")
}

fn params_rust(params: &[(String, Typ)]) -> String {
    params
        .iter()
        .map(|(n, t)| format!("{}: {}", sanitize(n), type_str(SourceLang::Rust, t)))
        .collect::<Vec<_>>()
        .join(", ")
}

fn field(lang: SourceLang, name: &str) -> String {
    match lang {
        SourceLang::Go => export_go(name),
        SourceLang::Rust => sanitize(name),
    }
}

fn bin_op(op: &str) -> &str {
    match op {
        "add" | "+" => "+",
        "sub" | "-" => "-",
        "mul" | "*" => "*",
        "div" | "/" => "/",
        "mod" | "%" => "%",
        "eq" | "==" => "==",
        "neq" | "!=" => "!=",
        "lt" | "<" => "<",
        "gt" | ">" => ">",
        "le" | "<=" => "<=",
        "ge" | ">=" => ">=",
        "land" | "&&" => "&&",
        "lor" | "||" => "||",
        "band" | "&" => "&",
        "bor" | "|" => "|",
        "xor" | "^" => "^",
        "shl" | "<<" => "<<",
        "shr" | ">>" => ">>",
        other => other,
    }
}

fn expr(lang: SourceLang, e: &Expr) -> String {
    match e {
        Expr::IntLit(n) => format!("{n}"),
        Expr::FloatLit(f) => format!("{:?}", f.0),
        Expr::BoolLit(b) => {
            if *b {
                "true".into()
            } else {
                "false".into()
            }
        }
        Expr::StringLit(s) => match lang {
            SourceLang::Go => format!("{:?}", s),
            SourceLang::Rust => format!("{:?}.to_string()", s),
        },
        Expr::Ident(n) => sanitize(n),
        Expr::Unary { op, expr: inner } => {
            let x = expr(lang, inner);
            match op.as_str() {
                "neg" | "-" => format!("(-{x})"),
                "not" | "!" => format!("(!{x})"),
                other => format!("({other}{x})"),
            }
        }
        Expr::Binary { op, lhs, rhs } => {
            format!("({} {} {})", expr(lang, lhs), bin_op(op), expr(lang, rhs))
        }
        Expr::Call { callee, args } => {
            let as_ = args
                .iter()
                .map(|a| expr(lang, a))
                .collect::<Vec<_>>()
                .join(", ");
            if let Expr::Field { base, name } = &**callee {
                return format!("{}.{}({as_})", expr(lang, base), field(lang, name));
            }
            format!("{}({as_})", expr(lang, callee))
        }
        Expr::Field { base, name } => format!("{}.{}", expr(lang, base), field(lang, name)),
        Expr::StructInit { name, fields } => {
            let fs = fields
                .iter()
                .map(|(n, v)| format!("{}: {}", field(lang, n), expr(lang, v)))
                .collect::<Vec<_>>()
                .join(", ");
            match lang {
                SourceLang::Go => format!("{}{{{fs}}}", sanitize(name)),
                SourceLang::Rust => format!("{} {{ {fs} }}", sanitize(name)),
            }
        }
        Expr::Index { base, index } => {
            format!("{}[{}]", expr(lang, base), expr(lang, index))
        }
        Expr::ArrayLit(items) => {
            let els = items
                .iter()
                .map(|i| expr(lang, i))
                .collect::<Vec<_>>()
                .join(", ");
            match lang {
                SourceLang::Go => format!("[]int64{{{els}}}"),
                SourceLang::Rust => format!("vec![{els}]"),
            }
        }
        Expr::Closure {
            params,
            body,
            captures,
            ..
        } => match lang {
            SourceLang::Go => {
                let ps = params_go(params);
                let mut inner = String::new();
                for s in body {
                    stmt(&mut inner, lang, s, 2);
                }
                format!("func({ps}) {{\n{inner}\t}}")
            }
            SourceLang::Rust => {
                let move_kw = if captures.is_empty() { "" } else { "move " };
                let ps = params_rust(params);
                let mut inner = String::new();
                for s in body {
                    stmt(&mut inner, lang, s, 2);
                }
                format!("{move_kw}|{ps}| {{\n{inner}    }}")
            }
        },
    }
}

fn pad(lang: SourceLang, indent: usize) -> String {
    match lang {
        SourceLang::Go => "\t".repeat(indent),
        SourceLang::Rust => "    ".repeat(indent),
    }
}

fn stmt(out: &mut String, lang: SourceLang, s: &Stmt, indent: usize) {
    let p = pad(lang, indent);
    let semi = if lang == SourceLang::Rust { ";" } else { "" };
    match s {
        Stmt::Let(name, typ, e) => match lang {
            SourceLang::Go => {
                out.push_str(&format!("{p}{} := {}\n", sanitize(name), expr(lang, e)));
            }
            SourceLang::Rust => {
                let ty = typ
                    .as_ref()
                    .map(|t| format!(": {}", type_str(lang, t)))
                    .unwrap_or_default();
                out.push_str(&format!(
                    "{p}let mut {}{} = {};\n",
                    sanitize(name),
                    ty,
                    expr(lang, e)
                ));
            }
        },
        Stmt::Assign(name, e) => {
            out.push_str(&format!(
                "{p}{} = {}{semi}\n",
                sanitize(name),
                expr(lang, e)
            ));
        }
        Stmt::IndexAssign { base, index, value } => {
            out.push_str(&format!(
                "{p}{}[{}] = {}{semi}\n",
                expr(lang, base),
                expr(lang, index),
                expr(lang, value)
            ));
        }
        Stmt::FieldAssign { base, name, value } => {
            out.push_str(&format!(
                "{p}{}.{} = {}{semi}\n",
                expr(lang, base),
                field(lang, name),
                expr(lang, value)
            ));
        }
        Stmt::Return(e) => match (lang, e) {
            (SourceLang::Go, Some(x)) => out.push_str(&format!("{p}return {}\n", expr(lang, x))),
            (SourceLang::Go, None) => out.push_str(&format!("{p}return\n")),
            (SourceLang::Rust, Some(x)) => out.push_str(&format!("{p}return {};\n", expr(lang, x))),
            (SourceLang::Rust, None) => out.push_str(&format!("{p}return;\n")),
        },
        Stmt::If {
            cond,
            then_body,
            else_body,
        } => {
            out.push_str(&format!("{p}if {} {{\n", expr(lang, cond)));
            for s in then_body {
                stmt(out, lang, s, indent + 1);
            }
            if !else_body.is_empty() {
                out.push_str(&format!("{p}}} else {{\n"));
                for s in else_body {
                    stmt(out, lang, s, indent + 1);
                }
            }
            out.push_str(&format!("{p}}}\n"));
        }
        Stmt::Loop { kind, cond, body } => match (lang, kind) {
            (SourceLang::Go, LoopKind::For { binding }) => {
                let iter = cond
                    .as_ref()
                    .map(|c| expr(lang, c))
                    .unwrap_or_else(|| "nil".into());
                out.push_str(&format!(
                    "{p}for _, {} := range {iter} {{\n",
                    sanitize(binding)
                ));
                for s in body {
                    stmt(out, lang, s, indent + 1);
                }
                out.push_str(&format!("{p}}}\n"));
            }
            (SourceLang::Go, _) => {
                match cond {
                    Some(c) => out.push_str(&format!("{p}for {} {{\n", expr(lang, c))),
                    None => out.push_str(&format!("{p}for {{\n")),
                }
                for s in body {
                    stmt(out, lang, s, indent + 1);
                }
                out.push_str(&format!("{p}}}\n"));
            }
            (SourceLang::Rust, LoopKind::For { binding }) => {
                let iter = cond
                    .as_ref()
                    .map(|c| expr(lang, c))
                    .unwrap_or_else(|| "[]".into());
                out.push_str(&format!("{p}for {} in {iter} {{\n", sanitize(binding)));
                for s in body {
                    stmt(out, lang, s, indent + 1);
                }
                out.push_str(&format!("{p}}}\n"));
            }
            (SourceLang::Rust, LoopKind::While) => {
                let c = cond
                    .as_ref()
                    .map(|c| expr(lang, c))
                    .unwrap_or_else(|| "true".into());
                out.push_str(&format!("{p}while {c} {{\n"));
                for s in body {
                    stmt(out, lang, s, indent + 1);
                }
                out.push_str(&format!("{p}}}\n"));
            }
            (SourceLang::Rust, LoopKind::Infinite) => {
                out.push_str(&format!("{p}loop {{\n"));
                for s in body {
                    stmt(out, lang, s, indent + 1);
                }
                out.push_str(&format!("{p}}}\n"));
            }
        },
        Stmt::Match { scrutinee, arms } => match lang {
            SourceLang::Go => {
                out.push_str(&format!("{p}switch {} {{\n", expr(lang, scrutinee)));
                for arm in arms {
                    let pat = arm.pattern.trim();
                    if pat == "_" || pat == "else" || pat == "default" {
                        out.push_str(&format!("{p}default:\n"));
                    } else if is_safe_pattern(pat) {
                        out.push_str(&format!("{p}case {pat}:\n"));
                    } else {
                        out.push_str(&format!("{p}default: // pattern\n"));
                    }
                    for s in &arm.body {
                        stmt(out, lang, s, indent + 1);
                    }
                }
                out.push_str(&format!("{p}}}\n"));
            }
            SourceLang::Rust => {
                out.push_str(&format!("{p}match {} {{\n", expr(lang, scrutinee)));
                for arm in arms {
                    let pat = arm.pattern.trim();
                    let pat = if is_safe_pattern(pat) { pat } else { "_" };
                    out.push_str(&format!("{p}    {pat} => {{\n"));
                    for s in &arm.body {
                        stmt(out, lang, s, indent + 2);
                    }
                    out.push_str(&format!("{p}    }}\n"));
                }
                out.push_str(&format!("{p}}}\n"));
            }
        },
        Stmt::Throw(e) => match lang {
            SourceLang::Go => out.push_str(&format!("{p}panic({})\n", expr(lang, e))),
            SourceLang::Rust => {
                out.push_str(&format!("{p}panic!(\"{{:?}}\", {});\n", expr(lang, e)))
            }
        },
        // Lossy: dump body; catch arms as comments (no full exception model).
        Stmt::Try { body, catches } => {
            out.push_str(&format!("{p}// try\n{p}{{\n"));
            for s in body {
                stmt(out, lang, s, indent + 1);
            }
            out.push_str(&format!("{p}}}\n"));
            for c in catches {
                out.push_str(&format!("{p}// catch {}\n", sanitize_line(&c.pattern)));
                for s in &c.body {
                    stmt(out, lang, s, indent);
                }
            }
        }
        Stmt::Propagate => out.push_str(&format!("{p}// propagate\n")),
        Stmt::Expr(e) => out.push_str(&format!("{p}{}{semi}\n", expr(lang, e))),
        Stmt::Break => out.push_str(&format!("{p}break{semi}\n")),
        Stmt::Continue => out.push_str(&format!("{p}continue{semi}\n")),
    }
}

fn sanitize(name: &str) -> String {
    let s: String = name
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();
    if s.is_empty() {
        "_".into()
    } else if s.as_bytes()[0].is_ascii_digit() {
        format!("_{s}")
    } else {
        s
    }
}

fn export_go(name: &str) -> String {
    let s = sanitize(name);
    let mut chars = s.chars();
    match chars.next() {
        Some(c) => format!("{}{}", c.to_ascii_uppercase(), chars.as_str()),
        None => "X".into(),
    }
}

fn module_within_limits(module: &UnifiedModule) -> bool {
    let mut nodes = 0usize;
    for d in &module.decls {
        if !count_decl(d, 0, &mut nodes) {
            return false;
        }
    }
    true
}

fn count_decl(d: &Decl, depth: u32, nodes: &mut usize) -> bool {
    if depth > MAX_EMIT_DEPTH {
        return false;
    }
    *nodes += 1;
    if *nodes > MAX_EMIT_NODES {
        return false;
    }
    match d {
        Decl::Function { body, .. } => count_stmts(body, depth + 1, nodes),
        Decl::Class { methods, .. } => methods.iter().all(|m| count_decl(m, depth + 1, nodes)),
        Decl::Global { init: Some(e), .. } => count_expr(e, depth + 1, nodes),
        _ => true,
    }
}

fn count_stmts(stmts: &[Stmt], depth: u32, nodes: &mut usize) -> bool {
    stmts.iter().all(|s| count_stmt(s, depth, nodes))
}

fn count_stmt(s: &Stmt, depth: u32, nodes: &mut usize) -> bool {
    if depth > MAX_EMIT_DEPTH {
        return false;
    }
    *nodes += 1;
    if *nodes > MAX_EMIT_NODES {
        return false;
    }
    match s {
        Stmt::Let(_, _, e) | Stmt::Assign(_, e) | Stmt::Throw(e) | Stmt::Expr(e) => {
            count_expr(e, depth + 1, nodes)
        }
        Stmt::Return(Some(e)) => count_expr(e, depth + 1, nodes),
        Stmt::Return(None) | Stmt::Propagate | Stmt::Break | Stmt::Continue => true,
        Stmt::IndexAssign { base, index, value } => {
            count_expr(base, depth + 1, nodes)
                && count_expr(index, depth + 1, nodes)
                && count_expr(value, depth + 1, nodes)
        }
        Stmt::FieldAssign { base, value, .. } => {
            count_expr(base, depth + 1, nodes) && count_expr(value, depth + 1, nodes)
        }
        Stmt::If {
            cond,
            then_body,
            else_body,
        } => {
            count_expr(cond, depth + 1, nodes)
                && count_stmts(then_body, depth + 1, nodes)
                && count_stmts(else_body, depth + 1, nodes)
        }
        Stmt::Loop { cond, body, .. } => {
            cond.as_ref()
                .map(|c| count_expr(c, depth + 1, nodes))
                .unwrap_or(true)
                && count_stmts(body, depth + 1, nodes)
        }
        Stmt::Match { scrutinee, arms } => {
            count_expr(scrutinee, depth + 1, nodes)
                && arms.iter().all(|a| count_stmts(&a.body, depth + 1, nodes))
        }
        Stmt::Try { body, catches } => {
            count_stmts(body, depth + 1, nodes)
                && catches
                    .iter()
                    .all(|c| count_stmts(&c.body, depth + 1, nodes))
        }
    }
}

fn count_expr(e: &Expr, depth: u32, nodes: &mut usize) -> bool {
    if depth > MAX_EMIT_DEPTH {
        return false;
    }
    *nodes += 1;
    if *nodes > MAX_EMIT_NODES {
        return false;
    }
    match e {
        Expr::Unary { expr, .. } => count_expr(expr, depth + 1, nodes),
        Expr::Binary { lhs, rhs, .. } => {
            count_expr(lhs, depth + 1, nodes) && count_expr(rhs, depth + 1, nodes)
        }
        Expr::StructInit { fields, .. } => fields
            .iter()
            .all(|(_, fe)| count_expr(fe, depth + 1, nodes)),
        Expr::Field { base, .. } => count_expr(base, depth + 1, nodes),
        Expr::ArrayLit(items) => items.iter().all(|it| count_expr(it, depth + 1, nodes)),
        Expr::Index { base, index } => {
            count_expr(base, depth + 1, nodes) && count_expr(index, depth + 1, nodes)
        }
        Expr::Call { callee, args } => {
            count_expr(callee, depth + 1, nodes)
                && args.iter().all(|a| count_expr(a, depth + 1, nodes))
        }
        Expr::Closure { body, .. } => count_stmts(body, depth + 1, nodes),
        _ => true,
    }
}

fn sanitize_line(s: &str) -> String {
    s.chars()
        .map(|c| if c == '\n' || c == '\r' { ' ' } else { c })
        .collect()
}

fn is_safe_pattern(s: &str) -> bool {
    if s.is_empty() {
        return false;
    }
    if s == "true" || s == "false" || s == "_" {
        return true;
    }
    if s.parse::<i64>().is_ok() {
        return true;
    }
    if s.len() >= 2 && s.starts_with('"') && s.ends_with('"') {
        return s[1..s.len() - 1]
            .chars()
            .all(|c| c != '"' && c != '\\' && c != '\n');
    }
    let mut chars = s.chars();
    match chars.next() {
        Some(c) if c.is_ascii_alphabetic() || c == '_' => {}
        _ => return false,
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core_ir::{Expr, Stmt, Typ};

    #[test]
    fn go_emits_fn_and_if() {
        let module = UnifiedModule::new(vec![Decl::Function {
            name: "answer".into(),
            params: vec![],
            ret: Typ::Int,
            body: vec![Stmt::If {
                cond: Expr::BoolLit(true),
                then_body: vec![Stmt::Return(Some(Expr::IntLit(42)))],
                else_body: vec![Stmt::Return(Some(Expr::IntLit(0)))],
            }],
            type_params: vec![],
        }]);
        let go = emit_source_module(&module, SourceLang::Go);
        assert!(go.contains("package main"), "{go}");
        assert!(go.contains("func answer()"), "{go}");
        assert!(go.contains("if true"), "{go}");
        assert!(go.contains("return 42"), "{go}");
    }

    #[test]
    fn rust_emits_fn_and_while() {
        let module = UnifiedModule::new(vec![Decl::Function {
            name: "loop_sum".into(),
            params: vec![("n".into(), Typ::Int)],
            ret: Typ::Int,
            body: vec![
                Stmt::Let("i".into(), Some(Typ::Int), Expr::IntLit(0)),
                Stmt::Loop {
                    kind: LoopKind::While,
                    cond: Some(Expr::Binary {
                        op: "lt".into(),
                        lhs: Box::new(Expr::Ident("i".into())),
                        rhs: Box::new(Expr::Ident("n".into())),
                    }),
                    body: vec![Stmt::Assign(
                        "i".into(),
                        Expr::Binary {
                            op: "add".into(),
                            lhs: Box::new(Expr::Ident("i".into())),
                            rhs: Box::new(Expr::IntLit(1)),
                        },
                    )],
                },
                Stmt::Return(Some(Expr::Ident("i".into()))),
            ],
            type_params: vec![],
        }]);
        let rs = emit_source_module(&module, SourceLang::Rust);
        assert!(rs.contains("fn loop_sum(n: i64) -> i64"), "{rs}");
        assert!(rs.contains("while"), "{rs}");
        assert!(rs.contains("let mut i: i64 = 0"), "{rs}");
    }

    #[test]
    fn go_and_rust_emit_struct() {
        let module = UnifiedModule::new(vec![
            Decl::Struct {
                name: "Point".into(),
                fields: vec![("x".into(), Typ::Int), ("y".into(), Typ::Int)],
                type_params: vec![],
            },
            Decl::Function {
                name: "origin".into(),
                params: vec![],
                ret: Typ::Named("Point".into()),
                body: vec![Stmt::Return(Some(Expr::StructInit {
                    name: "Point".into(),
                    fields: vec![("x".into(), Expr::IntLit(0)), ("y".into(), Expr::IntLit(0))],
                }))],
                type_params: vec![],
            },
        ]);
        let go = emit_source_module(&module, SourceLang::Go);
        let rs = emit_source_module(&module, SourceLang::Rust);
        assert!(go.contains("type Point struct"), "{go}");
        assert!(go.contains("Point{"), "{go}");
        assert!(rs.contains("struct Point"), "{rs}");
        assert!(rs.contains("Point {"), "{rs}");
    }
}
